/*
 * StuMainFrm.java
 *
 * Created on __DATE__, __TIME__
 */

package ui;

import javax.swing.JDialog;
import javax.swing.JOptionPane;



/**
 *
 * @author  __USER__
 */
public class StuMainFrm extends javax.swing.JFrame {

	/** Creates new form StuMainFrm */
	public StuMainFrm() {
		initComponents();
		//设置窗体居中显示
		this.setLocationRelativeTo(null);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();
		jMenu3 = new javax.swing.JMenu();
		jMenuItem2 = new javax.swing.JMenuItem();
		jMenuItem3 = new javax.swing.JMenuItem();
		jMenuItem1 = new javax.swing.JMenuItem();
		jMenu2 = new javax.swing.JMenu();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jMenu1.setText("\u7cfb\u7edf\u64cd\u4f5c");

		jMenu3.setText("\u67e5\u8be2");

		jMenuItem2.setText("\u5168\u90e8\u67e5\u8be2");
		jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem2ActionPerformed(evt);
			}
		});
		jMenu3.add(jMenuItem2);

		jMenuItem3.setText("\u6761\u4ef6\u67e5\u8be2");
		jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem3ActionPerformed(evt);
			}
		});
		jMenu3.add(jMenuItem3);

		jMenu1.add(jMenu3);

		jMenuItem1.setText("\u4fee\u6539\u5bc6\u7801");
		jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem1ActionPerformed(evt);
			}
		});
		jMenu1.add(jMenuItem1);

		jMenuBar1.add(jMenu1);

		jMenu2.setText("\u9000\u51fa");
		jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jMenu2MouseClicked(evt);
			}
		});
		jMenuBar1.add(jMenu2);

		setJMenuBar(jMenuBar1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 400,
				Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 279,
				Short.MAX_VALUE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {
		StuUpPwd sp = new StuUpPwd();
		sp.setVisible(true);
		sp.setTitle(getTitle());
		sp.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
	}

	private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {
		MohuSeleteFrm ms = new MohuSeleteFrm();
		ms.setVisible(true);
		ms.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
	}

	private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {
		SelectFrm sf = new SelectFrm();
		sf.setVisible(true);
		sf.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
	}

	private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {
		//弹出一个带选择按钮的提示框					
		// 位置 	  提示消息		消息框的标题       按钮的类型
		int choose = JOptionPane.showConfirmDialog(null, "是否退出？", "系统提示",
				JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
		if (choose == 0) {
			//退出程序
			//			System.exit(0);
			this.dispose();
		}
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new StuMainFrm().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenu jMenu2;
	private javax.swing.JMenu jMenu3;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JMenuItem jMenuItem1;
	private javax.swing.JMenuItem jMenuItem2;
	private javax.swing.JMenuItem jMenuItem3;
	// End of variables declaration//GEN-END:variables

}